### PR TITLE
Artwork and camera

### LINKED ISSUE #3: Finished tile set
Soft deadline: October 23rd

### LINKED ISSUE #4: Finished character sprite work
Soft deadline: October 23rd

### PR DESCRIPTION
**Pull request by karoluzas**
Created sprites for all the four enemy types.
Created water tiles. For now there should be enough tiles to create ~95% of everything in a given level. Also fixed the annoying gaps in between some tiles.
Created a new sprite for the player, gun and slash animation.

Added a camera that follows the player.

This PR is mainly concerned with assets, but some code changes did occur.

### CODE REVIEW

**Review by DeividasLT5 — COMMENTED** [review]
Artwork looks nice :)

**Comment by ernestas20111** [comment]
There seems to be a few bugs:
image
gun should probably switch side together with the player.
Recording 2022-10-25 at 19 11 56
Then there is a strange map switch for some tiles
However, slashing seems to work quite well

**Comment by ernestas20111** [comment]
image
Also not sure about this, but shouldn't those clones be destroyed? I mean if there will be a lot of bullets it might pollute the memory and slow down the game.

**Comment by karoluzas** [comment]
> Then there is a strange map switch for some tiles Other than that, slashing seems to work just fine

Yeah this is super weird. This happenes to me only when i delete the tileset png, so the tile pallete messes up. But I made a new one and everything is fine on my end.

> gun should probably switch side together with the player.

To speed up development I wanted to rush out this PR as fast as possible so the whole team had sprites to work with, so I deemed it not necessary to bog down with small details like this, unless it's a priority to fix it right now and not down the line.

**Comment by karoluzas** [comment]
> Also not sure about this, but shouldn't those clones be destroyed? I mean if there will be a lot of bullets it might pollute the memory and slow down the game.

Currently in code they are coded to be destroyed when colliding with something. But this PR is mainly concerned with art and collisions are worked on right now by one of our collegues I believe

**Comment by ernestas20111** [comment]
> > Also not sure about this, but shouldn't those clones be destroyed? I mean if there will be a lot of bullets it might pollute the memory and slow down the game.
> 
> Currently in code they are coded to be destroyed when colliding with something. But this PR is mainly concerned with art and collisions are worked on right now by one of our collegues I believe

Okey, then.
Everything else seems just fine.

**Review by ernestas20111 — APPROVED** [review]

**Comment by karoluzas** [comment]
> Then there is a strange map switch for some tiles

Sprites should be fixed now

**Pull request merged**
